language: python
os: linux
dist: xenial

python:
  - 3.7

services:
  - docker

install:
  # Setup a development virtual environment
  - make -C director venv-dev

before_script:
  # Download Codeclimate test reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  # Run linting checks
  - make -C director lint-code
  - make -C director lint-types
  - make -C director lint-docs
  # Run tests
  - make -C director cover
  # Build production Docker images
  - make -C director build
  - make -C router build

after_script:
  # Run Codeclimate test reporter
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT --prefix $TRAVIS_BUILD_DIR/director
  # Run Codecov test uploader
  - curl -s https://codecov.io/bash | bash
