version: "3.6"

services:

  router:
    build: ./router
    image: stencila/hub-router
    ports:
      - "9000:9000"
    environment:
      - BROKER_URL=${BROKER_URL}
      - DIRECTOR_URL=${DIRECTOR_URL}

  director:
    build: ./director
    image: stencila/hub-director
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}/database/dev.sqlite3:/home/director/dev.sqlite3
    environment:
      - BROKER_URL=${BROKER_URL}
      - DATABASE_URL=${DATABASE_URL}
      # These env vars are necessary to run Django
      # without HTTPS in a non-production environment
      - DJANGO_SECURE_SSL_REDIRECT=false
      - DJANGO_SECRET_KEY=not-a-secret
      # These env vars are likely to be removed soon
      # but are necessary at present
      - DJANGO_SENTRY_DSN
      - DJANGO_POSTHOG_KEY
      - DJANGO_JWT_SECRET=not-a-secret
      - DJANGO_SENDGRID_API_KEY=not-a-secret

  broker:
    build: ./broker
    image: stencila/hub-broker
    ports:
      - "6379:6379"

  scheduler:
    build: ./scheduler
    image: stencila/hub-scheduler
    volumes:
      - ${PWD}/database/dev.sqlite3:/home/scheduler/dev.sqlite3
    environment:
      - BROKER_URL=${BROKER_URL}
      - DATABASE_URL=${DATABASE_URL}

  worker:
    build: ./worker
    image: stencila/hub-worker
    environment:
      - BROKER_URL=${BROKER_URL}
      - DIRECTOR_URL=${DIRECTOR_URL}
      - DIRECTOR_AUTH=user:user
