# This docker-compose file is intended for development and testing.
# However, it is also used as a basis for Kubernetes deployments.
# Consequently, some properties have been added to improve conversion to 
# Kubernetes configs when using Kompose:
# - labels starting with `kompose`
# - `.env` file in `env_file` so that services are linked to the `env-configmap.yaml`

version: "3.6"

services:

  router:
    build: ./router
    image: stencila/hub-router
    labels:
      kompose.service.type: loadbalancer
      kompose.service.expose: "true"
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - director

  director:
    build: ./director
    image: stencila/hub-director
    ports:
      - "8000:8000"
    env_file:
      - .secrets
    environment:
      # These env vars are necessary to run Django
      # without HTTPS in a non-production environment
      - DJANGO_SECURE_SSL_REDIRECT=false
      - DJANGO_SECRET_KEY=not-a-secret
      # These env vars are likely to be removed soon
      # but are necessary at present
      - DJANGO_SENTRY_DSN
      - DJANGO_POSTHOG_KEY
      - DJANGO_JWT_SECRET=not-a-secret
      - DJANGO_SENDGRID_API_KEY=not-a-secret
    depends_on:
      - database
      - broker

  database:
    build: ./database
    image: stencila/hub-database
    ports:
      - "5432:5432"
    env_file:
      - .secrets

  broker:
    build: ./broker
    image: stencila/hub-broker
    ports:
      - "5672:5672"
    env_file:
      - .secrets

  scheduler:
    build: ./scheduler
    image: stencila/hub-scheduler
    env_file:
      - .secrets
    depends_on:
      - database
      - broker

  monitor:
    build: ./monitor
    image: stencila/hub-monitor
    env_file:
      - .secrets
    depends_on:
      - director
      - broker

  worker:
    build: ./worker
    image: stencila/hub-worker
    env_file:
      - .secrets
    depends_on:
      - broker