# This docker-compose file is intended for development and testing.
# However, it is also used as a basis for Kubernetes deployments.
# Some properties have been added to improve conversion to Kubernetes configs
# using Kompose:
# - labels starting with `kompose`
# - `env_file` to services to generate and bind a config map

version: "3.6"

services:

  router:
    build: ./router
    image: stencila/hub-router
    labels:
      kompose.service.type: loadbalancer
      kompose.service.expose: "true"
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      - BROKER_URL=${BROKER_URL}
      - DIRECTOR_URL=${DIRECTOR_URL}

  director:
    build: ./director
    image: stencila/hub-director
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}/database/dev.sqlite3:/home/director/dev.sqlite3
    env_file:
      - .env
    environment:
      - BROKER_URL=${BROKER_URL}
      - DATABASE_URL=${DATABASE_URL}
      # These env vars are necessary to run Django
      # without HTTPS in a non-production environment
      - DJANGO_SECURE_SSL_REDIRECT=false
      - DJANGO_SECRET_KEY=not-a-secret
      # These env vars are likely to be removed soon
      # but are necessary at present
      - DJANGO_SENTRY_DSN
      - DJANGO_POSTHOG_KEY
      - DJANGO_JWT_SECRET=not-a-secret
      - DJANGO_SENDGRID_API_KEY=not-a-secret

  broker:
    build: ./broker
    image: stencila/hub-broker
    ports:
      - "6379:6379"

  scheduler:
    build: ./scheduler
    image: stencila/hub-scheduler
    volumes:
      - ${PWD}/database/dev.sqlite3:/home/scheduler/dev.sqlite3
    env_file:
      - .env
    environment:
      - BROKER_URL=${BROKER_URL}
      - DATABASE_URL=${DATABASE_URL}

  monitor:
    build: ./monitor
    image: stencila/hub-monitor
    env_file:
      - .env
    environment:
      - BROKER_URL=${BROKER_URL}
      - DIRECTOR_URL=${DIRECTOR_URL}

  worker:
    build: ./worker
    image: stencila/hub-worker
    env_file:
      - .env
    environment:
      - BROKER_URL=${BROKER_URL}
      - DIRECTOR_URL=${DIRECTOR_URL}
      - DIRECTOR_AUTH=user:user
