swagger: '2.0'

info:
  title: Stencila API
  version: 1.0
  description: |
    The Stencila API is under rapid development. So,

      - not all of the endpoints that are documented here are implemented!
      - not all of the endpoint that are implemented are documented here!
      - much of the documentation here may not match what is currently implemented!

    Please bear with us, we are working hard to get the API settled down and to version 1.0.

    The API uses the ampersand `@` to denote calls to methods of components. We use `address/of/component@method` instead of `address/of/component/method` so that it is possible to resolve where a component address ends and the method name starts. We use `@` instead of `.` to easily differentiate method URL endpoints from raw file endpoints. The ampersand is a valid charater for a HTTP URL (see page 17 of http://tools.ietf.org/html/rfc1738).


{% if MODE != 'local' %}
host: stenci.la
{% endif %}
basePath: /
schemes:
{% if MODE != 'local' %}
  - https
{% else %}
  - http
{% endif %}
consumes:
  - application/json
produces:
  - application/json
  - text/html

paths:

  ###########################################################################
  # Components
  ###########################################################################

  /{address}@boot:

    put:
      summary: Boot up a component.
      description: |
        If the user has write access to the component then a new session will be started for it.
      tags:
        - Components
      parameters:
        - name: address
          in: path
          required: true
          type: string
      responses:
        200:
          description: Successfully activated.
          schema:
            properties:
              rights:
                type: string
              session:
                $ref: '#/definitions/Session'

  /{address}@activate:

    put:
      summary: Activate a component by starting a session for it.
      tags:
        - Components
      parameters:
        - name: address
          in: path
          required: true
          type: string
      responses:
        200:
          description: Successfully activated.
          schema:
            $ref: '#/definitions/Session'

  /{address}@deactivate:

    put:
      summary: Deactivate a component by stopping the current session for it.
      tags:
        - Components
      parameters:
        - name: address
          in: path
          required: true
          type: string
      responses:
        200:
          description: Successfully deactivated.
          schema:
            $ref: '#/definitions/Session'

  /{address}@session:

    put:
      summary: Get the active session, if any, for the component.
      tags:
        - Components
      parameters:
        - name: address
          in: path
          required: true
          type: string
      responses:
        200:
          description: Active session for the component.
          schema:
            $ref: '#/definitions/Session'

  /{address}@ping:

    put:
      summary: Ping the component's active session
      tags:
        - Components
      parameters:
        - name: address
          in: path
          required: true
          type: string
      responses:
        200:
          description: Session is still active

  /{address}@save:

    put:
      summary: Save a component.
      tags:
        - Components
      parameters:
        - name: address
          in: path
          required: true
          type: string
      responses:
        200:
          description: Successfully saved.

  /{address}@commit:

    put:
      summary: Commit changes to a component.
      tags:
        - Components
      parameters:
        - name: address
          in: path
          required: true
          type: string
        - name: data
          in: body
          required: true
          schema:
            type: object
            properties:
              message:
                type: string
      responses:
        200:
          description: Successfully committed.
          properties:
            revision:
              type: string
              required: true

  /{address}@commits:

    get:
      summary: Get the commits for a component.
      tags:
        - Components
      parameters:
        - name: address
          in: path
          required: true
          type: string
      responses:
        200:
          schema:
            type: array
            items:
              type: object
              properties:
                foo:
                  type: string

  /{address}@sync:

    put:
      summary: Synchronise a component with it's origin.
      tags:
        - Components
      parameters:
        - name: address
          in: path
          required: true
          type: string
      responses:
        200:
          description: Successfully synchronised.
          properties:
            revision:
              type: string
              required: true

  /{address}@received:

    put:
      summary: Notify that a component repository has received updates.
      description: |
        This endpoint is intended for the `curator` role only. 
        It is called when the repository is updated (e.g. by a `git push`).
      tags:
        - Components
      parameters:
        - name: address
          in: path
          required: true
          type: string
        - name: data
          in: body
          required: true
          schema:
            type: object
            properties:
              token:
                type: string
      responses:
        200:
          description: Successfully notified.

  ###########################################################################
  # Stencils
  ###########################################################################

  /{address}@content:

    get:
      summary: Get the content of a stencil.
      tags:
        - Stencils
      parameters:
        - name: address
          in: path
          required: true
          type: string
        - name: format
          in: query
          type: string
          default: 'html'
      responses:
        200:
          schema:
            properties:
              revision:
                type: string
                required: true
              format:
                type: string
                required: true
              content:
                type: string
                required: true

    put:
      summary: Set the content of a stencil.
      tags:
        - Stencils
      parameters:
        - name: address
          in: path
          required: true
          type: string
        - name: data
          in: body
          required: true
          schema:
            type: object
            properties:
              revision:
                type: string
                required: true
              format:
                type: string
                required: true
              content:
                type: string
                required: true
      responses:
        200:
          schema:
            properties:
              revision:
                type: string
                required: true
              status:
                type: integer
                required: true

  ###########################################################################
  # Sheets
  ###########################################################################

  /{address}@update:

    put:
      summary: Update the source of one or more cells
      tags:
        - Sheets
      parameters:
        - name: address
          in: path
          required: true
          type: string
        - name: data
          in: body
          required: true
          schema:
            type: array
            items:
              properties:
                id:
                  type: string
                  required: true
                source:
                  type: string
                  required: true
      responses:
        200:
          schema:
            type: array
            items:
              properties:
                id:
                  type: string
                  required: true
                type:
                  type: string
                  required: true
                value:
                  type: string
                  required: true


  ###########################################################################
  # Snippets
  ###########################################################################

  /snippets:

    get:
      summary: List snippets.
      tags:
        - Snippets
      responses:
        200:
          schema:
            type: array
            items:
              $ref: '#/definitions/SnippetBrief'

  /snippets/{id}:

    get:
      summary: Read a snippet.
      tags:
        - Snippets
      parameters:
        - name: id
          type: string
          in: path
          required: true
          description: ID of the snippet
      responses:
        200:
          schema:
            $ref: '#/definitions/Snippet'

    put:
        summary: Create or update a snippet.
        description: |
          If the snippet does not yet exist then it will be created, otherwise it will be updated.
        tags:
          - Snippets
        parameters:
          - name: id
            type: string
            in: path
            required: true
            description: ID of the snippet
          - name: data
            in: body
            required: false
            schema:
              $ref: '#/definitions/Snippet'

        responses:
          200:
            schema:
              $ref: '#/definitions/Snippet'

  ###########################################################################
  # Sessions
  ###########################################################################


  /sessions:

    get:
      summary: List sessions.
      tags:
        - Sessions
      responses:
        200:
          description: List of sessions
          schema:
            type: array
            items:
              $ref: '#/definitions/Session'

  /sessions/{id}:

    get:
      summary: Read a session.
      tags:
        - Sessions
      parameters:
        - name: id
          type: number
          in: path
          required: true
          description: ID of the session
      responses:
        200:
          description: Data on the session
          schema:
            $ref: '#/definitions/Session'

  /sessions/{id}@ping:

    put:
      summary: Ping a session.
      tags:
        - Sessions
      parameters:
        - name: id
          type: number
          in: path
          required: true
          description: ID of the session
      responses:
        200:
          description: OK


  /sessions/{id}@stop:

    put:
      summary: Stop a session.
      tags:
        - Sessions
      parameters:
        - name: id
          type: number
          in: path
          required: true
          description: ID of the session
      responses:
        200:
          description: Data on the session
          schema:
            $ref: '#/definitions/Session'

  ###########################################################################
  # Me
  ###########################################################################

  /me:

    get:
      summary: Read the current user.
      tags:
        - Me
      responses:
        200:
          description: Data on the user
          schema:
            $ref: '#/definitions/Me'


  ###########################################################################
  # Tokens
  ###########################################################################

  /tokens:

    get:
      summary: List user tokens.
      tags:
        - Tokens
      responses:
        200:
          description: List of user tokens
          schema:
            type: array
            items:
              $ref: '#/definitions/Token'

    post:
      summary: Create a user token.
      description: |
        User tokens
      tags:
        - Tokens
      parameters:
        - name: data
          in: body
          required: false
          schema:
            $ref: '#/definitions/Token'
          description: |
            Data on the user token; only `name` and `notes` can be input.
      responses:
        200:
          description: Data on the new user token
          schema:
            $ref: '#/definitions/Token'

  /tokens/{id}:

    get:
      summary: Read a user token.
      tags:
        - Tokens
      parameters:
        - name: id
          type: number
          in: path
          required: true
          description: ID of the token
      responses:
        200:
          description: Data on the user token
          schema:
            $ref: '#/definitions/Token'

    patch:
      summary: Update a user token.
      tags:
        - Tokens
      parameters:
        - name: id
          type: number
          in: path
          required: true
          description: ID of the token
        - name: data
          in: body
          required: false
          schema:
            $ref: '#/definitions/Token'
          description: |
            Data on the user token; only `name` and `notes` can be updated.
      responses:
        200:
          description: Data on the user token
          schema:
            $ref: '#/definitions/Token'

    delete:
      summary: Delete a user token.
      tags:
        - Tokens
      parameters:
        - name: id
          type: number
          in: path
          required: true
          description: ID of the token
      responses:
        200:
          description: Successfully deleted


  ###########################################################################
  # Users
  ###########################################################################

  /users:

    get:
      summary: List users.
      tags:
        - Users
      responses:
        200:
          description: A list of users.
          schema:
            type: array
            items:
              $ref: '#/definitions/User'

  /users/{username}:

    get:
      summary: Read a user.
      description: |
        Not all data on the user is available. Use `/me` to get more detailed data on the
        user that is currently authenticated.
      tags:
        - Users
      parameters:
        - name: username
          type: string
          in: path
          required: true
          description: Username of the user
      responses:
        200:
          description: Data on the user
          schema:
            $ref: '#/definitions/User'

  ###########################################################################
  # Builds
  ###########################################################################

  /builds:

    get:
      summary: List builds.
      tags:
        - Builds
      responses:
        200:
          description: A list of builds.
          schema:
            type: array
            items:
              $ref: '#/definitions/Build'

    post:
      summary: Create a build.
      tags:
        - Builds
      parameters:
        - name: data
          in: body
          required: false
          schema:
            $ref: '#/definitions/Build'
          description: |
            The fields `platform` and `url` are optional; `user` and `datetime` will be ignored.
      responses:
        200:
          description: A list of builds.
          schema:
            $ref: '#/definitions/Build'

  /builds/{id}:

    get:
      summary: Read a Build.
      tags:
        - Builds
      parameters:
        - name: id
          type: string
          in: path
          required: true
          description: ID of the build
      responses:
        200:
          description: Data on the user
          schema:
            $ref: '#/definitions/Build'



definitions:

  Account:
    type: object
    required:
      - name
      - type
    properties:
      name:
        type: string
      type:
        type: string

  Build:
    type: object
    properties:
      id:
        type: string
      package:
        type: string
      flavour:
        type: string
      version:
        type: string
      commit:
        type: string      
      platform:
        type: string
      url:
        type: string
      user:
        $ref: '#/definitions/User'
      datetime:
        type: string
        format: date-time

  Component:
    properties:
      address:
        type: string
        description: Address of this component
      type:
        type: string
        description: Type of this component (e.g. stencil, theme)
      url:
        type: string
        description: URL for this component
      tiny:
        type: string
        description: Tiny URL for this component
      account:
        $ref: '#/definitions/Account'
        description: |
          Account which owns this component. Determined as the account which owns the component's address, or a it's parent address.
      public:
        type: boolean
        description: |
          Is this component public? Determined by whether the component's address, or a it's parent address, is public.
      rights:
        type: string
        description: Access rights for the current user for this component ('READ','UPDATE',etc)
      favourites:
        type: int
        description: Number of times this component has been favourited
      favourited:
        type: boolean
        description: Has this component been favourtied by the current user?
      forks:
        type: int
        description: Number of times this component has been forked


  Me:
    properties:
      username:
        type: string
      date_joined:
        type: string
        format: date-time
      last_login:
        type: string
        format: date-time

  Session:
    type: object
    properties:
      id:
        type: string
      user:
        $ref: '#/definitions/User'
      component:
        $ref: '#/definitions/Component'
      url:
        type: string
      websocket:
        type: string
      ready:
        type: boolean
      status:
        type: string

  Snippet:
    description: Specification of a snippet. See the schema on Github
    type: object
    properties:
      id:
        type: string
      summary:
        type: string

  SnippetBrief:
    description: Brief summary of a snippet
    type: object
    properties:
      id:
        type: string
      summary:
        type: string

  Token:
    properties:
      id:
        type: integer
        format: int32
      name:
        type: string
      version:
        type: string
        description: Version number of the token coding
      string:
        type: string
        description: Encoded token string
      issued:
        type: string
        format: date-time
      expires:
        type: string
        format: date-time
      notes:
        type: string


  User:
    properties:
      username:
        type: string
